# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Triplebyte web crawler test site
email: buck@triplebyte.com
description: > # this means to ignore newlines until "baseurl:"
  This site has lots of amusing gotchas for people who attempt to scrape it!
baseurl: "/web-crawler-test-site" # the subpath of your site, e.g. /blog
url: "http://triplebyte.github.io/" # the base hostname & protocol for your site
twitter_username: bshlgrs
github_username: bshlgrs

# Build settings
markdown: kramdown
